### ISSUE TITLE
框架不错，关键是写的时候不提示，复制粘贴有点坑

### ISSUE THREAD

**Issue by jianjianhao** [zhenglibao/FlexLib#1]

**Comment by zhenglibao** [comment]
恩，这个确实是个问题，后续需要研究一下

**Comment by zhenglibao** [comment]
Visual Studio Code这个ide不错，还可以扩展，有机会研究一下怎么扩展，更好的支持布局文件

**Comment by CainLuo** [comment]
有属性布局的Demo么? 用XML累人啊.....

**Comment by zhenglibao** [comment]
代码里边有例子啊，Objective-c和swift两个版本的都有

**Comment by klzhong69** [comment]
或者兼容android的界面布局就更完美了

**Comment by zhenglibao** [comment]
研究了一下，貌似visual studio code支持自定义配置，参考：
https://github.com/zhenglibao/FlexLib/wiki/Visual-Studio-Code%E6%99%BA%E8%83%BD%E6%8F%90%E7%A4%BA
