### ISSUE TITLE
支持Android吗？

### ISSUE THREAD

**Issue by yilongmd** [zhenglibao/FlexLib#100]
Android是否也可以用同一套UI

**Comment by zhenglibao** [comment]
不支持，安卓本身的布局就很好用了，内置就支持各种布局方式和flexbox

**Comment by AAChartModel** [comment]
Google 已经有一套 flex 布局的官方库了. 作者再写一套意义不大.

**Comment by AAChartModel** [comment]
谷歌官方 FlexBox 布局框架传送门: https://github.com/google/flexbox-layout
