### ISSUE TITLE
喜欢flex布局的便捷，和Texture框架比较怎么选择？

### ISSUE THREAD

**Issue by Ox8BADFOOD** [zhenglibao/FlexLib#107]

**Comment by Ox8BADFOOD** [comment]
有办法分离结构和样式吗？

**Comment by Ox8BADFOOD** [comment]
用类似wxml wxss 这样特有的文件命来提示，是不是比直接用xml好呢？

**Comment by zhenglibao** [comment]
flexlib是一个轻量级的布局库，和masonry、mylayout等作用是一样的，而texture功能要丰富复杂的多，主要看你的需求了。
xml的作用你可以类比xib，其实不存在好坏之分，能满足需求就是好的

**Comment by Ox8BADFOOD** [comment]
样式能像sass一样能计算吗？

**Comment by zhenglibao** [comment]
现在暂时不支持计算

**Comment by Ox8BADFOOD** [comment]
xml里UIView*5 这样的emmet语法有办法支持下吗？写起来会更爽

**Comment by zhenglibao** [comment]
这种可以考虑给vscode提个插件，在插件里做补全，直接让xml支持这种写法不太合适

**Comment by Ox8BADFOOD** [comment]
请问能做屏幕缩放吗？
类似：WXSS中，引入了rpx；weex布局采用基于750的等比例缩放

**Comment by zhenglibao** [comment]
不支持屏幕缩放
