### ISSUE TITLE
how to user Macro FLEXSET in swift

### ISSUE THREAD

**Issue by Ox8BADFOOD** [zhenglibao/FlexLib#109]
please give me a suggestion,thanks

**Comment by zhenglibao** [comment]
用oc在扩展中实现比较方便，用swift的话不能使用FLEXSET宏，可以参照FLEXSET的命名方式用swift来写对应的方法，方法要用@objc修饰

**Comment by Ox8BADFOOD** [comment]
@objc func setFlextitle(_ sValue:NSString,Owner:NSObject) -> (){
        title.text = sValue as String
}
