### ISSUE TITLE
预览模块如何只在 debug 下使用

### ISSUE THREAD

**Issue by wayone** [zhenglibao/FlexLib#112]
我希望只在 debug 模式下使用预览模块。
我是这么写的：

  pod 'FlexLib', '2.9.1', :configurations => ['Release'] #XML布局
  pod 'FlexLib', '2.9.1', :configurations => ['Debug'] #XML布局
  pod 'FlexLib/preview', :configurations => ['Debug']

但是 pod install 报错。
The subspecs of `FlexLib` are linked to different build configurations for the `Pods-XXX` target. CocoaPods does not currently support subspecs across different build configurations.

请问，如何解决呢？

**Comment by zhenglibao** [comment]
这个应该和debug或者release没关系，你应该是希望preview只在线下环境使用，线上环境去掉吧

可以在xcode里面创建一个线上的target，一个线下的target，然后在podfile里面设置为线下的target使用preview，线上的不使用就可以了

**Comment by wayone** [comment]
预览模块，在功能上就体现出了它是在开发的时候用的，刚好对应 debug，比较自然，cocoapods 也支持这样的设定。创建多个 target 也能解决，之后，我每次新建文件、添加文件时，都需要考虑选择哪个 target，这个产生了很多额外操作。希望能支持 debug 模式下引入。

**Comment by zhenglibao** [comment]
> 预览模块，在功能上就体现出了它是在开发的时候用的，刚好对应 debug，比较自然，cocoapods 也支持这样的设定。创建多个 target 也能解决，之后，我每次新建文件、添加文件时，都需要考虑选择哪个 target，这个产生了很多额外操作。希望能支持 debug 模式下引入。

仔细分下pod的提示，是pod不支持把子模块设置为不同的配置，这个得修改pod实现才行，建议你还是使用多target的模式

**Comment by wayone** [comment]
相比较于多 target，通过改 pod 来支持，能给使用者带来更多便利
