### ISSUE TITLE
如何在自定义的宏中添加参数，然后用在 xml 里

### ISSUE THREAD

**Issue by wayone** [zhenglibao/FlexLib#113]
以下两个方法都不支持添加参数
void FlexRegisterMacro(NSString* macroName,FlexMacro value);
double FlexCalcExpression(NSString* expression);

**Comment by zhenglibao** [comment]
这个自定义宏不支持添加参数，请问什么场景下需要使用参数？另外你希望这个参数如何在xml中传递呢？

**Comment by wayone** [comment]
场景：某个距离不是死的，要根据屏幕宽度做比例，例如：$marginLeft: 10*某个比例。
使用方式：在 OC 里面，宏里面传递参数很常见。就是说，我写的这个宏，他能够传入一个参数，然后处理一下，再返回一个值。假设 A() 是一个宏，希望这么使用，$marginLeft:A(10)。

如果宏的实现比较简单，用表达式也行。但是我要在很多地方使用，所以同样的表达式我要写很多遍，感觉用 A(10) 这种比较方便，并且把实现统一到一起了，如果以后要修改，只改一个地方就行了。

**Comment by zhenglibao** [comment]
> 场景：某个距离不是死的，要根据屏幕宽度做比例，例如：$marginLeft: 10*某个比例。 使用方式：在 OC 里面，宏里面传递参数很常见。就是说，我写的这个宏，他能够传入一个参数，然后处理一下，再返回一个值。假设 A() 是一个宏，希望这么使用，$marginLeft:A(10)。
> 
> 如果宏的实现比较简单，用表达式也行。但是我要在很多地方使用，所以同样的表达式我要写很多遍，感觉用 A(10) 这种比较方便，并且把实现统一到一起了，如果以后要修改，只改一个地方就行了。

后续版本可以考虑支持参数
