### ISSUE TITLE
自定义宏，不管用

### ISSUE THREAD

**Issue by wayone** [zhenglibao/FlexLib#114]
版本 3.1.2
<img width="969" alt="iShot2022-01-04 18 19 20" src="https://user-images.githubusercontent.com/10210378/148044424-3ff9ea4e-bf17-45b9-8f70-aa439ef0dacf.png">

在 appDelegate 的方法 application:didFinishLaunchingWithOptions: 里注册宏

FlexRegisterMacro(@"aa_ratio", ^double{
        return (double)58.0;
    });

然后在 xml 里使用 marginTop:aa_ratio, 无效。

**Comment by wayone** [comment]
使用 height:ScreenWidth 也无效

**Comment by zhenglibao** [comment]
要在height前添加$，表示这是一个表达式

![image](https://user-images.githubusercontent.com/1912567/148152678-fd4c10b3-d26b-43a3-a30c-b7c3aceb210d.png)

**Comment by wayone** [comment]
使用$后，使用 ScreenWidth 管用，自定义宏不管用，自定义宏的定义方式就是面上写的

**Comment by zhenglibao** [comment]
> 使用$后，使用 ScreenWidth 管用，自定义宏不管用，自定义宏的定义方式就是上面写的

是不是注册时机晚于xml的初始化了？或者有个demo的话可以传上来看下
