### ISSUE TITLE
xml文件里，第一次触摸到 UITextField 后，就滑动不了了。

### ISSUE THREAD

**Issue by LuDamon** [zhenglibao/FlexLib#118]
FlexScrollView 是第一节点，FlexContainerView是第二节点，FlexContainerView的 子 view 中有UILabel 和 UITextField.
当拖动页面时，如果触摸的是 UITextField，则拖动无响应。
如果触摸的是UILabel，是正常的。

示例仓库：https://github.com/LuDamon/FlexLibTest.git
演示视频

https://user-images.githubusercontent.com/14227723/158772075-9e3eb03b-00bd-4270-ab78-b50af42b913e.mov

：

**Comment by LuDamon** [comment]
已解决

**Comment by nodkH** [comment]
如果这不是使用问题，那这个库用起来还真是得谨慎...
