### ISSUE TITLE
FlexShowToast有时好使，有时不好使

### ISSUE THREAD

**Issue by songxing10000** [zhenglibao/FlexLib#119]
.... failure:^(NSError *error) {
        NSString *str = [NSString stringWithFormat:@"%@%@", @"保存失败：", error.localizedDescription];
        
        FlexShowToast(str, 2);
    }];

**Comment by zhenglibao** [comment]
这个建议使用专业的第三方toast库，该方法主要是内部使用的

**Comment by songxing10000** [comment]
了解了
