### ISSUE TITLE
建议新增获取自定义Bundle中资源的功能

### ISSUE THREAD

**Issue by XJYao** [zhenglibao/FlexLib#12]
组件化开发时资源文件（如图片、字体表、颜色表）往往会放在自定义的Bundle中，我看了flexlib源码发现目前没有获取自定义Bundle中资源的功能，建议增加。

**Comment by zhenglibao** [comment]
我理解的是你希望设置属性时能够使用自定义bundle中的资源，比如UIImageView中的source属性可能会设置为自定义bundle中的图片，如果是这样的话实际上是支持的。

自定义属性的时候使用的是这个宏：
#define FLEXSET(propName)               \
-(void)setFlex##propName:(NSString*)sValue Owner:(NSObject*)owner
第一个参数是xml中设置的字符串值，第二个就是owner，一般也就是viewcontroller，这样通过owner可以获取到对应的bundle。

除了框架里边预定义的属性，你也可以自己导出你所需要的属性。

不确定是否准确理解了你的意思，有问题继续讨论。

**Comment by XJYao** [comment]
嗯，是这个意思。 但是有个问题，在VC中重写bundleForImages方法只能返回一个bundle，可一个VC里如果需要使用多个bundle呢？
