### ISSUE TITLE
代码提示警告修复

### ISSUE THREAD

**Issue by xxf-nku** [zhenglibao/FlexLib#125]
官方提供的代码补全插件中出现了重复定义	
分别是位于448行和607行的borderWidth
以及位于1872和1870行的no
具体代码如下
"borderWidth":{
		"prefix": "borderWidth",
		"body": [
			"borderWidth",
		],
	},
	"no":{
		"prefix": "no",
		"body": [
			"no",
		],
	},

**Comment by zhenglibao** [comment]
谢谢，已删除重复定义
