### ISSUE TITLE
UIView 叠加

### ISSUE THREAD

**Issue by Jas67810** [zhenglibao/FlexLib#16]
<UIView layout="height:100%,width:100%" attr="name:root"/>
     <UIView  layout="height:100%,width:100%" attr="name:sub1"/>
     <UIView  layout="height:100%,width:100%" attr="name:sub2">
         ........... /*其它布局*/
     </UIView>
</UIView>

想布局叠加。类似 sub1 作为背景，显示在 sub2 的下面。如何实现。（类似Android里面的relativelayout 的效果）

**Comment by Jas67810** [comment]
是否有demo进行查看，比如 sub1 是个 listview ，sub2有多个按键之类的






在 2018-08-20 09:27:12，"zhenglibao" <notifications@github.com> 写道：


可以对sub1或者sub2使用绝对布局，也就是position: absolute，这种情况下可以设置其绝对位置。默认情况下都是使用流失布局，也就是position: relative。

**Comment by zhenglibao** [comment]
例子如下：
```xml
<UIView layout="flex:1" attr="bgColor:white">
    <UIView name="view1" layout="flex:1" attr="bgColor:green"/>
    <UIView name="view2" layout="position:absolute,right:20,bottom:20,width:50,height:50" attr="bgColor:red"/>
</UIView>
```
view1采用流式布局，占据父窗口的全部区域，view2是一个绝对定位的窗口，浮动在view1上面，距离右边界和下边界分别为20
