### ISSUE TITLE
关于UIButton的问题

### ISSUE THREAD

**Issue by iamcoderloser** [zhenglibao/FlexLib#17]
我一直尝试在xml中设置字体大小，以及文字的对齐方式，一直不得法。

**Comment by zhenglibao** [comment]
建议使用FlexTouchView来代替UIButton，不建议使用UIButton。因为UIButton自身实现的原因，难以对UIButton进行定制以实现一些复杂的效果。

如果一定要使用UIButton的话，可以在UIButton的分类中用FLEXSET宏导出一个你自己的属性，然后就可以在xml中使用了，如下：

FLEXSET(myFont)
{
     self.titleLabel.font = [UIFont systemFontOfSize: [sValue floatValue]];
}

新增加的属性在xml中不会有提示，可以通过修改vscode的配置文件来实现智能提示，参考这里：
https://github.com/zhenglibao/FlexLib/wiki/Visual-Studio-Code%E6%99%BA%E8%83%BD%E6%8F%90%E7%A4%BA

**Comment by iamcoderloser** [comment]
非常感谢你的解答，问题已经解决了！
