### ISSUE TITLE
TableView高度自适应

### ISSUE THREAD

**Issue by JiamingTu** [zhenglibao/FlexLib#18]
不知道为什么我把原tableView 和 cell 的源文件 放到我的工程上运行，结果高度没有自适应，demo运行的是可以的

**Comment by zhenglibao** [comment]
如果想使用评估高度的话，需要满足如下条件：
1.使用最新版1.9.0，之前的版本是不支持的
2.tableview需要设置rowHeight为UITableViewAutomaticDimension
3.tableview的estimatedRowHeight设置为大于0的数值

**Comment by JiamingTu** [comment]
> 如果想使用评估高度的话，需要满足如下条件：
> 1.使用最新版1.9.0，之前的版本是不支持的
> 2.tableview需要设置rowHeight为UITableViewAutomaticDimension
> 3.tableview的estimatedRowHeight设置为大于0的数值

果然是版本的问题，非常感谢
