### ISSUE TITLE
智能提示很弱

### ISSUE THREAD

**Issue by tang7547** [zhenglibao/FlexLib#19]
我不知道，赋值你的智能提示代码有问题还是怎么回事，看你的智能提示很好！自动标签闭合，提示比较到位，我的就是不行，自己写闭合标签，一点不友好提示

**Comment by zhenglibao** [comment]
看这个地址： https://github.com/zhenglibao/FlexLib/wiki/Visual-Studio-Code%E6%99%BA%E8%83%BD%E6%8F%90%E7%A4%BA

智能提示约定
去除控件前缀将自动替换成完整的组件，如
label ===> <UILabel name="" layout="" attr=""/>
textview ===> <FlexTextView name="" layout="" attr="fontSize:14,color:black,textAlign:left"/>
view ===> <UIView layout="" attr=""> </UIView>

其他提示的内容将直接等效于所提示的内容，如
UILabel ====> UILabel
white ====> white
