### ISSUE TITLE
支持 Swift 4.0 吗？

### ISSUE THREAD

**Issue by bmcciscoding** [zhenglibao/FlexLib#2]
我想在 Swift 4.0 的项目上使用，但是好像并不支持

-[GDataXMLNode attributeForName:]: unrecognized selector sent to instance 0x60400004abc0
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GDataXMLNode attributeForName:]: unrecognized selector sent to instance 0x60400004abc0'

**Comment by zhenglibao** [comment]
暂时还没有精力搞swift版本 :(

**Comment by zhenglibao** [comment]
写了个demo，在swift工程里边使用flexlib，另外可以参考readme里边的内容。

之前这个报错是因为一个bug，与swift没关系，主要是xml里边包含了注释导致的。
