### ISSUE TITLE
是否支持自定义的view

### ISSUE THREAD

**Issue by xiaoyaoyouzi163com** [zhenglibao/FlexLib#20]
.xml里是否支持使用自定义的view？

**Comment by zhenglibao** [comment]
答案是支持自定义的view：
1. 如果你自己写的UIView的派生类支持通过init方法创建，那么很简单，直接在xml中使用你view即可（当然在vscode中不会有这个view的提示，这个需要单独配置vscode才行）。如果你的view不支持通过init方法创建，那么在xml中声明后，则必须重写owner的createView:Name:方法来返回你的自定义view的实例。

2.如果需要在xml中希望使用自定义的属性，则必须通过FLEXSET宏在分类中来扩展该属性
