### ISSUE TITLE
如何更新xml中某一控件的LayoutAttr？

### ISSUE THREAD

**Issue by xiaoyaoyouzi163com** [zhenglibao/FlexLib#21]
如何更新xml中某一控件的LayoutAttr？
直接通过-(void)setLayoutAttr:(NSString*) name
               Value:(NSString*) value;
设置，好像是没有效果的。demo中也没有看到类似的代码

**Comment by zhenglibao** [comment]
可以通过以下三个方法来更新布局属性：
```objective-c
-(void)setLayoutAttr:(NSString*) name
               Value:(NSString*) value;
-(void)setLayoutAttrs:(NSArray<FlexAttr*>*)attrs;
-(void)setLayoutAttrStrings:(NSArray<NSString*>*)stringAttrs;
```
更新完之后需要调用 markDirty 进行刷新

**Comment by xiaoyaoyouzi163com** [comment]
好的。估计是我之前没有刷新的缘故。刚试了一下可以了

**Comment by xiaoyaoyouzi163com** [comment]
还想问一下。这个markDirty方法是用谁来调用比较合理？xml文件布局最顶部的view还是说需要更新的控件部分最小的父视图？

**Comment by xiaoyaoyouzi163com** [comment]
好的，谢谢
