### ISSUE TITLE
UITextField 能否在在左右设置leftView,rightView

### ISSUE THREAD

**Issue by tang7547** [zhenglibao/FlexLib#22]
是否能够在这个控件里设置leftView和rightViewn吗？我看到demo里没有这方面的控件，这里好像没有button那种控件，设置设选中和不选择状态的值吗？我特别期望能这个布局能够跟简化的到att{bgColor:red,fontSize:12},这种就好了，现在控件上就是好乱眼睛，  <style name="s3">
        <attr name="bgColor">white</attr>
        <attr name="fontSize">16</attr>
        <attr name="color">#333333</attr>
    </style>   =
、   <UILabel layout="width:100%" attr="fontSize:16,textAlign:center,color:red,text:Please touch me and move\,\r\n这是测试touch功能的控件"/>

**Comment by tang7547** [comment]
说的没有button控件

**Comment by zhenglibao** [comment]
这两个属性需要用代码来设置，其实你也可以在xml中给UITextField添加两个子view，通过设置各种margin和padding来达到leftView和rightView的作用
