### ISSUE TITLE
Entity: line 4: parser error : Extra content at the end of the document

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#24]
我在实时预览的时候设置了BaseUrl，在模拟器界面command+R 后就出现黑屏 并且报错Entity: line 4: parser error : Extra content at the end of the document
<img width="863" alt="2018-10-09 2 52 08" src="https://user-images.githubusercontent.com/20568661/46651665-58041280-cbd3-11e8-95f9-8365167bfa31.png">
<img width="355" alt="2018-10-09 2 52 37" src="https://user-images.githubusercontent.com/20568661/46651667-589ca900-cbd3-11e8-831b-0526bb035efd.png">

**Comment by zhenglibao** [comment]
这个错误说明接受到的不是一个合法的xml字符串，你需要确认在模拟器的浏览器中能够正常访问到对应的xml文件。

**Comment by lztbwlkj** [comment]
我的做法是：
1、pod安装FlexLib 
2、引入头文件 
3、继承FlexBaseVC
4、创建TestLayout.xml
5、实现-(NSString *)getFlexName 并return @"TestLayout";

**Comment by zhenglibao** [comment]
可以这样调试，在 FlexFetchHttpRes 这个方法里边设置断点，看看当你reload的时候url是什么，然后把url拷贝到浏览器中看能否得到正确的xml文件内容，这个一般都是由于baseurl配置不正确导致无法访问造成的。

**Comment by lztbwlkj** [comment]
很感谢 按你说的方法已经解决了，是URL的问题

**Comment by nicaho** [comment]
[请问如何解决URL的问题阿。我新建的xml是找不到的，但之前已存在的xml可以找到。类也设置了@objc(xxxx)【用的是Swift】
![image](https://user-images.githubusercontent.com/5061802/74700201-caf8b100-523d-11ea-842f-23d57f62f285.png)
