### ISSUE TITLE
XML 解析出来的 frame 为 （0，0，0，0）

### ISSUE THREAD

**Issue by Jas67810** [zhenglibao/FlexLib#25]
<?xml version="1.0" encoding="utf-8"?>
<UIView
    layout="flex:1,justifyContent:flex-end,width:100%,height:100%"
    attr="bgColor:#ffffffff">
    
    
    
    <UIView name="capturepanel" layout="width:100%,height:100%,justifyContent:space-around,alignItems:center">
        <UIView  name="previewUIView" layout="width:100%,flex:1,flexDirection:row,justifyContent:space-around,alignItems:center" attr="bgColor:#ff000000">
            
        </UIView>
        <UIView  layout="width:100%,height:200,flexDirection:row,justifyContent:space-around,alignItems:center">
            <UIImageView layout="margin:30,width:70,height:70" attr=""/>
            <UIView layout="flex:1,height:100%,justifyContent:space-around,alignItems:center"  attr="">
                <UIImageView name="captureButton" layout="margin:40,width:80,height:80" attr="source:cycle.png"/>
            </UIView>
            <UIImageView layout="margin:30,width:70,height:70" attr="source:arrow_right.png"/>
        </UIView>
    </UIView>
</UIView>

我在一个自定义的view里面，然后在initWithFrame 里面调用 
FlexFrameView * frameview = [[FlexFrameView alloc] initWithFlex:@"bellus3dcapture" Frame:self.frame Owner:self];
[self addSubview:frameview];
LogDebug(@"previewUIView:%@, captureButton:%@", _previewUIView, _captureButton);
将xml布局加载进自定义的view，并添加Log进行调试。结果Log显示  
previewUIView:<UIView: 0x10db02e80; frame = (0 0; 0 0); layer = <CAGradientLayer: 0x1c403d960>>, captureButton:<UIImageView: 0x10db038a0; frame = (0 0; 0 0); opaque = NO; userInteractionEnabled = NO; layer = <CAGradientLayer: 0x1c403dd00>>

请问如何解决

**Comment by Jas67810** [comment]
Sorry, 是我弄错了，UIImageView转 Button出错

**Comment by zhenglibao** [comment]
建议使用FlexTouchView代替UIButton，使用起来更加的灵活方便

**Comment by Jas67810** [comment]
1，我自定义了一个ArcView，继承自UIView。然后只复写setFrame用于debug
@implementation ArcView
- (void)setFrame:(CGRect)frame
{
    LogDebug(@"setFrame:%@",NSStringFromCGRect(frame));
}
@end
2，将 ArcView 写进XML里面。
<UIView layout="position:absolute,flex:1,width:100%,height:100%,justifyContent:space-around,alignItems:center"  attr="">
                    
                    <ArcView name="captureFaceView" layout="width:80%,height:80%,flex:1"/>
                </UIView>
3,使用如下方法进行加载显示
FlexFrameView * frameview = [[FlexFrameView alloc] initWithFlex:@"bellus3dcapture" Frame:self.frame Owner:self];
    [self addSubview:frameview];
    [self layoutIfNeeded];
    LogDebug(@"captureFaceView:%@\ncaptureFaceImageView:%@", _captureFaceView, _captureFaceImageView);
4，结果Log显示如下
018-10-12 14:38:33:006 UnretekFace3D[991:292431] -[ArcView setFrame:] 第110行 setFrame:{{0, 0}, {0, 0}}
2018-10-12 14:38:33:036 UnretekFace3D[991:292431] -[ArcView setFrame:] 第110行 setFrame:{{37.333333333333336, 393.33333333333331}, {300, 98.666666666666686}}
2018-10-12 14:38:33:038 UnretekFace3D[991:292431] -[Bellus3DAR3DCaptureView commitBellus3DAR3DCaptureViewInit] 第63行 captureFaceView:<ArcView: 0x102715bc0; frame = (0 0; 0 0); layer = <CAGradientLayer: 0x280d1eac0>>
从Log中可以看出  setFrame 运行了两次，第二次已经将View的大小设置，但是为什么Log还显示frame = (0 0; 0 0); 
如上现象原因是什么。需要如何解决

**Comment by Jas67810** [comment]
在 XML 中布局的View，即使设定了大小。View 在读取显示时，会调用 initWithFrame ，但是这里传进来的一直是 （0，0，0，0），导致初始话内部控件时，无法正常显示（例如自定义View里面，有个UILab， UILab会根据自定义View 的frame决定UILab自己的frame）。需要如何处理

**Comment by Jas67810** [comment]
在 XML 中布局的View，即使设定了大小。View 在读取显示时，会调用 initWithFrame ，但是这里传进来的一直是 （0，0，0，0），导致初始话内部控件时，无法正常显示（例如自定义View里面，有个UILab， UILab会根据自定义View 的frame决定UILab自己的frame）。需要如何处理
