### ISSUE TITLE
加载本地文件资源

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#26]
1.加载本地system.style资源: 
  除了使用@:这个关键标识符,对文件路径有什么要求？
2、加载本地图片等资源：
 除了使用source:这个关键字, 对文件路径有设么要求?

**Comment by zhenglibao** [comment]
1. style扩展名的文件必须打包到mainBundle中，使用的时候直接使用文件名即可
2. source关键字对应的加载逻辑如下：
```objective-c
FLEXSET(source)
{
    UIImage* img = [UIImage imageNamed:sValue inBundle:[owner bundleForImages] compatibleWithTraitCollection:nil];
    self.image = img ;
}
```
如果对应的owner没有重载bundleForImages方法的话，这个就会从mainBundle加载图片，如果重载的话就会从对应的bundle中加载，加载的时候只使用文件名即可，对路径没有要求

**Comment by lztbwlkj** [comment]
我该如何控制是否重载bundleForImages方法？
是否可以加载image.assets中资源文件

**Comment by zhenglibao** [comment]
你可以在owner中重载bundleForImages，只要返回对应的bundle即可，owner就是你用来声明变量和点击事件的那个类。
也可以自己用FLEXSET宏声明你自己的属性，重写加载逻辑

**Comment by lztbwlkj** [comment]
我明白了 🙏
