### ISSUE TITLE
FlexBaseVC导航栏和FlexFrameView横竖屏

### ISSUE THREAD

**Issue by GuiLQing** [zhenglibao/FlexLib#28]
FlexBaseVC的子视图隐藏了导航栏之后视图没有自动上移
FlexFrameView怎样才能跟FlexBaseVC一样自动支持横竖屏

**Comment by zhenglibao** [comment]
第一个解决办法：重写getSafeArea方法，返回隐藏导航栏之后对应的inset
第二个需要在旋转屏幕后用代码调整FlexFrameView的frame，这个可以在你的基类里边进行统一的处理
