### ISSUE TITLE
UITableView 能支持group分组吗？

### ISSUE THREAD

**Issue by zxq911** [zhenglibao/FlexLib#29]
目前用法都是plain style，但是有些情况下会用到 grouped，请问能否兼容支持下，把UITableView支持下flexlib，然后开放重写的方法。

**Comment by zhenglibao** [comment]
这个是支持的，做法是在owner里边重写createView方法，返回grouped的tableview对象，如下：

```objective-c
-(UIView*)createView:(Class)cls Name:(NSString*)name
{
    if( [@"your name in xml" isEqualString:name]==NSOrderedSame)
         return [[UITableView alloc]initWithFrame:CRectZero style:UITableViewStyleGrouped]];
}
```
引起这个问题的原因是group模式的tableview无法通过init方法初始化，也无法在初始化通过简单设置属性来修改类型，因此只能通过这种自定义初始化的方式来实现

**Comment by lztbwlkj** [comment]
如果一个界面多个tableView 一个分组,一个不分组呢？

**Comment by zhenglibao** [comment]
根据不同的名字返回不同的值就可以了吧

**Comment by zhenglibao** [comment]
在xml中给每个tableView绑定一个名字，然后在createView里边使用这个名字
```xml
<UITableView name="t1"/>
<UITableView name="t2"/>
```
然后在createView里边比较这个t1和t2
