### ISSUE TITLE
发现一个热更新问题 

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#30]
我发现目前tableView中 我修改了Cell.xml中的某一个样式，必须重新运行app，按command+R组合键虽然刷新了当前界面，但是tableView并没有重载数据。

**Comment by lztbwlkj** [comment]
另外问一下:flex这个布局属性是开启flex的布局开关吗

**Comment by zhenglibao** [comment]
不是，flex:1等价于    flexGrow:1, flexShrink:1
xml中的所有的view都是开启flex布局的，如果设置hidden=true则会关掉flex布局，另外一种关掉的方法是 display:none，不过不建议使用

**Comment by lztbwlkj** [comment]
![852f35ef5e14db064658784620beb67a](https://user-images.githubusercontent.com/20568661/47071778-f83ae680-d226-11e8-8f82-d464ccdbab90.jpg)
![2018-10-17 4 13 55](https://user-images.githubusercontent.com/20568661/47072011-b0688f00-d227-11e8-93ae-38dbb849230e.png)
横屏下顶部会有一点点留白。横屏返回重新进入就没有了。 灰色部分是我设置了self.view.backgroundColor = [UIColor lightGrayColor];
设备iphone 7真机。 IOS 12.0.1

**Comment by zhenglibao** [comment]
这个已知问题，主要是FlexBaseVC::getSafeArea有问题，不过这个方法本来设计出来就是用来重写的（这个方法不可能覆盖所有情况），因此问题也不大，如果碰到有问题的话重写这个方法就好了

**Comment by lztbwlkj** [comment]
那app支持横竖屏切换，就要监听去更改getSafeArea的方法？

**Comment by zhenglibao** [comment]
不用啊，横竖屏切换的时候就会调用getSafeArea来调整布局，你只管重写这个方法就好了

**Comment by lztbwlkj** [comment]
这个getSafeArea:方法,只要屏幕方向有变化就会调用吗？

**Comment by zhenglibao** [comment]
屏幕方向变化肯定会调用，另外任何时候需要刷新布局的话都会被调用，比如弹起键盘等
