### ISSUE TITLE
tableView的高度Cell自适应

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#31]
tableView 的Cell中我隐藏row==3 的title标签，可是cell的高度还是和没隐藏一样，不是自动调整的，不知道这个算不算bug

**Comment by zhenglibao** [comment]
这个隐藏完需要调用 reloadRowsAtIndexPaths 这个方法

**Comment by lztbwlkj** [comment]
我隐藏了之后重新运行程序的
这是Cell中的隐藏代码，是不是我的方式不对？
 if (indexPath.row == 3) {
            title.hidden = YES;
            content.hidden = YES;
        }else{
            title.hidden = NO;
            content.hidden = NO;
        }
}

**Comment by zhenglibao** [comment]
你重写了heightFor...方法吗？如果没有重写而使用评估高度的话取决于你的xml是如何写的，如果重写了这个方法，得看你这个方法返回了什么值

**Comment by lztbwlkj** [comment]
这个heightFor ......方法使用的是Demo的代码,没有任何变化

**Comment by zhenglibao** [comment]
你是在demo的基础上修改的？能把修改过的部分完整的发出来吗？我测试一下

**Comment by lztbwlkj** [comment]
https://github.com/lztbwlkj/FlexLibTest.git 我都提交在这里了。

**Comment by zhenglibao** [comment]
你的问题是隐藏控件的方法在计算高度的时候并没有被调用到
```objective-c
-(void)setData:(NSDictionary*)data ForHeight:(BOOL)forHeight indexPath:(nonnull NSIndexPath *)indexPath
{
    if(!forHeight){
        if (indexPath.row == 3) {
            title.hidden = YES;
            content.hidden = YES;
        }else{
            title.hidden = NO;
            content.hidden = NO;
        }
        name.text = [data objectForKey:@"name"];
        date.text = [data objectForKey:@"date"];
        type.text = [data objectForKey:@"type"];
        title.text = [data objectForKey:@"title"];
    }
    content.text = [data objectForKey:@"content"];
}
```

**Comment by lztbwlkj** [comment]
🙏🙏感谢
