### ISSUE TITLE
能具体说明一下HOT Preview的使用方法吗，set preview base url这里的url到底是什么？

### ISSUE THREAD

**Issue by GuiLQing** [zhenglibao/FlexLib#32]

**Comment by zhenglibao** [comment]
详细的配置流程见这里：https://github.com/zhenglibao/FlexLib/wiki/Hot-preview

实时热预览的原理其实非常简单，在你的工作目录上开启一个http服务器，然后app就可以通过http协议拉取你工作目录上的xml文件，但是app如何获取xml文件的完整url呢？ 完整url = previewurl + 文件名.xml
这个previewurl就是你在设置页面的preview url，说白了就是用来拼最后的完整url用的。

**Comment by lztbwlkj** [comment]
HOT Preview简单来说就是你更新了本地.xml布局代码,不用重新运行程序,就可以看到修改后的结果,比如 运行的时候view的是bgColor:wihte, 后面我又修改了view的bgColor:red, 那么你可以点击模拟器然后command+R（也可以开启Preview Base Url文本框下的在线加载资源开关）就可以看到view的bgColor变红色了(前提是你配置好了preview base url)。
Preview Base Url:就是你.xml的预览路径，🌰：我的项目名在桌面(FLexTest)  .xml在工程中的xml文件夹中那么.xml的preview base Url为：http://本机IP地址+端口号/FlexTest/xml/ ，具体如何配置可以去https://github.com/zhenglibao/FlexLib/wiki/Hot-preview,说的很详细

以上是我的理解。
