### ISSUE TITLE
TextView 在cell 中高度变化

### ISSUE THREAD

**Issue by JiamingTu** [zhenglibao/FlexLib#33]
我想实现TextView在cell中，TextView高度可以变化，所以在cell 中这样实现，cell可以自适应高度，可是变化的尺寸会有偏差（如图 蓝色是self.planTextView.rootView ），求指导还有更好的实现方法吗
```
- (instancetype)initWithFlex:(NSString *)flexName reuseIdentifier:(NSString *)reuseIdentifier {
    if (self = [super initWithFlex:flexName reuseIdentifier:reuseIdentifier]) {   
        self.planTextView.rootView.onDidLayout = ^() {
            UITableView *tableView = self.superview.superview;
            [tableView beginUpdates];
            [tableView endUpdates];
        };
    }
    return self;
}
```

<img width="364" alt="lololo" src="https://user-images.githubusercontent.com/27000400/47157946-14b94a80-d31d-11e8-8c61-8b4af6eeb707.png">

![image](https://user-images.githubusercontent.com/27000400/47158051-5944e600-d31d-11e8-8f09-b61725f229c9.png)

**Comment by zhenglibao** [comment]
这个当cell高度发生变化的时候你需要 调用  reloadRowsAtIndexPaths 方法，不让uitableview怎么会刷新呢

**Comment by JiamingTu** [comment]
> 这个当cell高度发生变化的时候你需要 调用 reloadRowsAtIndexPaths 方法，不让uitableview怎么会刷新呢

使用
```
    [tableView beginUpdates];
    [tableView endUpdates];
```
效果应该是一样的
关键reload后 键盘会收起来😂

**Comment by zhenglibao** [comment]
reload后你可以再把键盘打开😀
