### ISSUE TITLE
.style文件怎么生成的

### ISSUE THREAD

**Issue by GuiLQing** [zhenglibao/FlexLib#35]
能不能有多个.style文件

**Comment by zhenglibao** [comment]
可以，没有限制。直接用文本编辑器生成一个就行

**Comment by GuiLQing** [comment]
你的那个.style是exec文件，而且显示也有代码格式和颜色

**Comment by GuiLQing** [comment]
你的那个.style是exec文件，而且显示也有代码格式和颜色

**Comment by zhenglibao** [comment]
不是exec，就是一个xml文件，是你mac的设置导致的显示为exec的，可能刚好这个style扩展名和系统里的某个一样了

**Comment by GuiLQing** [comment]
嗯，我知道怎么回事了，本来是没颜色的，把它变成exec就带颜色了。
![2018-10-19 17 15 40](https://user-images.githubusercontent.com/27814327/47209322-a29b4100-d3c2-11e8-948e-33cca13a9ce8.png)

![2018-10-19 17 13 08](https://user-images.githubusercontent.com/27814327/47209189-4f28f300-d3c2-11e8-9c81-72bb28621c39.png)
