### ISSUE TITLE
OC项目用Flex会自动适配横屏，swift不会

### ISSUE THREAD

**Issue by GuiLQing** [zhenglibao/FlexLib#36]

**Comment by zhenglibao** [comment]
你看一下demo里边的swift工程有问题吗？
另外，有的情况下（如页面包含tabcontroller）会导致页面安全区的判断有问题，这个时候可以重写getSafeArea来纠正，最简单的办法是直接返回(0,0,0,0)，这样直接控制controller.view的区域即可。
