### ISSUE TITLE
两个视图层叠怎么弄

### ISSUE THREAD

**Issue by GuiLQing** [zhenglibao/FlexLib#37]
比如说有个view是{0, 0, 375, 400}，另外一个view是{0, 300, 375, 200}

**Comment by GuiLQing** [comment]
如果需要在页面加载完成之后另外添加视图，该在哪个地方写

**Comment by GuiLQing** [comment]
你的FlexScrollView里面有FlexParentView* _subview; FlexRootView* _contentView;这两个视图，当我设置scrollview的horzScroll:true的时候，这两个视图只有scrollView的一半宽

**Comment by GuiLQing** [comment]
horzScroll:true的时候有问题

**Comment by zhenglibao** [comment]
> FlexScrollView也有问题，我设置横向滚动，就像横向商品分页一样，但是无论怎么去布局里面控件的layout，显示都是不变的

贴一下你的xml
