### ISSUE TITLE
ModalView不显示

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#38]
TouchView多次快速点击后。点击事件调用了但是ModalView不显示了

Demo地址https://github.com/lztbwlkj/FlexLibTest.git

**Comment by zhenglibao** [comment]
第一次点击 ModalView显示出来，第二次快速点击，取消ModalView的显示，第二次点击到ModalView上了

**Comment by lztbwlkj** [comment]
那第三次应该显示ModalView 但是不显示了  你可以在我的Demo中复现这个异常

**Comment by zhenglibao** [comment]
复现了，具体原因还不清楚，你可以先在touchview层面禁止连续快速点击来防止
