### ISSUE TITLE
请问朋友圈这种图片怎么操作?

### ISSUE THREAD

**Issue by HolmesZhao** [zhenglibao/FlexLib#4]
![simulator screen shot - iphone se - 2017-12-25 at 17 00 07](https://user-images.githubusercontent.com/19728934/34336797-1c104440-e995-11e7-90dd-163f0a7a9935.png)

----

这里的九宫格图片, 高度是如果代码不给 height 这个layout 值, 九宫格内的图片就会根据 image 的大小进行高度延展, 怎么才能给他这个宽高比呢? 我尝试了自定义一个 UIImageView , 重写 setFrame 方法, 强制改成 1:1 , 但是cell 的高度是根据我 xml 中的 height 布局的....

**Comment by zhenglibao** [comment]
可以使用layout中aspectRatio这个属性，该属性定义的是 宽度和高度的比例，比如你设置 width为30%，然后设置aspectRatio为1，则高度自动和宽度相同

**Comment by HolmesZhao** [comment]
原来如此, 谢谢老大~没注意到这个属性

**Comment by zhenglibao** [comment]
具体的可以参考： https://facebook.github.io/yoga/docs/aspect-ratio/#main_wrap

**Comment by YuYangArray** [comment]
您好，我碰到了一个类似的问题。
![wx20181112-145550](https://user-images.githubusercontent.com/17544458/48331442-13b0da00-e68b-11e8-859c-1c84b9e0afba.png)
因为图片本身比例问题，显示的比例需要在1：2到1：1之间浮动。我注意到有maxHeight,minHeight,aspectRatio这三个属性，但好像都不能满足。
有类似 maxHeight:width*1 或者 maxAspectRatio:1 这种方式吗？
