### ISSUE TITLE
使用FlexLib做的UI组件，在RN中使用全部失效

### ISSUE THREAD

**Issue by nb-tpl** [zhenglibao/FlexLib#42]
使用FlexLib做的UI组件，桥接到RN后，在RN中使用时全都失效，不会自动渲染了怎么办...

**Comment by nb-tpl** [comment]
主要使用了FlexBaseTableCell 和 FlexFrameView，组件中使用Frame布局的视图没有出问题

**Comment by nb-tpl** [comment]
😂...略衰...我试试，谢啦

**Comment by stelalae** [comment]
我现在也遇到react-native-cli 构建的工程里自带有yoga，和flexlib的依赖yoga有冲突了。能不能新增一个RN版本共存的release？谢谢
