### ISSUE TITLE
*** no method setFlexcolor:Owner:

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#44]
![2018-10-25 4 41 46](https://user-images.githubusercontent.com/20568661/47487476-16cb5e00-d875-11e8-8f8f-f8dee9c20320.png)
我使用了未定义的方法？还是说我有部分组件把layout属性用在了attr上面

**Comment by zhenglibao** [comment]
width, height, alignItems, justifyContent这些属性都是layout属性，你给写在了attr里边

**Comment by lztbwlkj** [comment]
希望这里的log可以指示出xml第几行的label，这样就方便很多

**Comment by zhenglibao** [comment]
> 希望这里的log可以指示出xml第几行的label，这样就方便很多

这个能做出来当然好，不过根据目前的做法很难实现😭

**Comment by lztbwlkj** [comment]
哇 好难受 我实在找不到是那个label 设置了这个 我看了半天都合适的
