### ISSUE TITLE
FlexScrollView问题

### ISSUE THREAD

**Issue by junjiansome** [zhenglibao/FlexLib#48]
FlexScrollView 通过FlexBaseVC的xml添加 然后在控制器中FlexFrameView通过xml方法生成对象 FlexScrollView对象添加FlexFrameView对象为子对象 结果FlexScrollView对象中的FlexRootView子控件高度为0 导致FlexRootView对象加载在高度为0的父类中 无法点击也无法拖动

**Comment by zhenglibao** [comment]
FlexFrameView设计出来只有一个目的，就是用来加载xml，而且FlexFrameView的实例本身并不使用flex，因此能够像其他view一样直接设置frame，但是这个类有个问题，就是不能用在xml里边，因为这个与他的设计初衷是违背的。

如果想在xml里边使用另外一个xml的话，可以使用FlexCustomBaseView,demo里边有用这个类把xml封装成控件的例子。

最后一点，不要直接往FlexScrollView上添加子view，可以在xml内部定义一个UIView或者FlexContainerView，然后往这个view上面添加

**Comment by junjiansome** [comment]
好的
