### ISSUE TITLE
关于字体支持

### ISSUE THREAD

**Issue by YuYangArray** [zhenglibao/FlexLib#49]
由于我的项目中有自己加入的字体
在寻找相关字体方法中，发现仅支持以下两种字体，能否考虑增加对自添加的字体的支持
if([@"bold" compare:fontName]==NSOrderedSame)
        return [UIFont boldSystemFontOfSize:fontSize];
    
if([@"italic" compare:fontName]==NSOrderedSame)
        return [UIFont italicSystemFontOfSize:fontSize];

**Comment by YuYangArray** [comment]
抱歉，自添加字体是支持。是我字体名写的有误。打扰了。

**Comment by Ox8BADFOOD** [comment]
<UILabel name="" class="" layout="height:20" attr="
            font:PingFangSC-Regular|18,
            color:#333333,
            lineBreakMode:truncatingTail,
            linesNum:1,
            text:100次,
            textAlign:center,
" />

**Comment by Ox8BADFOOD** [comment]
`<UILabel name="" class="" layout="height:20" attr="
            font:PingFangSC-Regular|18,
            color:#333333,
            lineBreakMode:truncatingTail,
            linesNum:1,
            text:100次,
            textAlign:center,
        " />`
