### ISSUE TITLE
tableView重用队列

### ISSUE THREAD

**Issue by YuYangArray** [zhenglibao/FlexLib#50]
我在
if (cell == nil) {
    cell = [[QWPhotoHeadTVCell alloc] initWithFlex:nil reuseIdentifier:@"QWPhotoHeadTVCell"];
}
中打了断点，发现根本不会走到断点处。

然后我在cell中重写的- (void)onInit方法中打了断点，发现走的逻辑是
[FlexBaseTableCell dequeueReusableCellWithIdentifier:@""]；
[FlexBaseTableCell internalInit:nil]；
[FlexBaseTableCell onInit]；
然后我在自定义的cell中的- (void)onInit，打印了self的地址，发现基本上没有太多重复的。
感觉是没有没有使用重用队列，而是每次重新创建了新的cell。

**Comment by zhenglibao** [comment]
看执行断点，能够正常重用

<img width="1135" alt="reuse" src="https://user-images.githubusercontent.com/1912567/48196166-a51f0400-e38c-11e8-9281-93624b1ec807.png">

**Comment by zhenglibao** [comment]
看执行断点，能够正常重用

![reuse 2](https://user-images.githubusercontent.com/1912567/48196563-d64c0400-e38d-11e8-8d5e-cb418e72b33e.png)

**Comment by YuYangArray** [comment]
我后来也尝试过，发现我前面有注册重用队列
[self.tableView registerClass:[XXXX class] forCellReuseIdentifier:@"XXXX"];
就不会走cell == nil
注释上方代码后，会走cell == nil，但是好像每次都是新的cell，因为cell的地址不一样。
而且你这个断点不是cell == nil里面，是cell不为空的情况。
建议还是在 return cell； 前打印cell地址，看看是否cell地址不同。

**Comment by zhenglibao** [comment]
dequeueResuableCellWithIdentifier方法返回非空的cell不正说明重用了吗？请问逻辑有问题吗？

**Comment by YuYangArray** [comment]
我询问这个问题的原因是因为，zai
