### ISSUE TITLE
xml 出来的View 重新布局

### ISSUE THREAD

**Issue by Jas67810** [zhenglibao/FlexLib#51]
我有个View用xml布局的。分上下两部分。上部分高度不固定 flex:1 , 下部分高度固定 20. 
然后使用 FlexFrameView 加载它
 [[FlexFrameView alloc] initWithFlex:@"xmlname"
                                          Frame:CGRectMake(0, 0, 200，100)
                                          Owner:self];
并将该  FlexFrameView 加进200X100大小的View里面，此时显示正常OK。
然后因为业务原因，我会将 200X100的View 改成 200X50大小的View。这时候 FlexFrameView 需要如何处理，才能显示正常。

**Comment by zhenglibao** [comment]
直接修改FlexFrameView的frame即可
