### ISSUE TITLE
封装自定义View

### ISSUE THREAD

**Issue by YuYangArray** [zhenglibao/FlexLib#53]
加载到普通ViewController上的view我看到的例子里有
CGRect rcFrame = CGRectMake(0, 0, [[UIScreen mainScreen] bounds].size.width, 0);
    FlexFrameView* header = [[FlexFrameView alloc]initWithFlex:@"TableHeader" Frame:rcFrame Owner:self];
    header.flexibleHeight = YES;
    [header layoutIfNeeded];
 _table.tableHeaderView = header;

但是这种用法好像需要在self中定义TableHeader文件中的name。
由于需要复用，且赋值较多。所以我想封装一个用xml布局能加到普通ViewController的View。
那么这个view的.h和.m文件需要怎么处理呢？需要继承哪个类啊？

**Comment by zhenglibao** [comment]
封装成组件的话需要继承自 FlexCustomBaseView，封装出来的组件可以直接用代码创建并制定frame，也可以用在其他的xml中，可以参考Demo中的AttachmentView

**Comment by YuYangArray** [comment]
我按照你说的，自定义了view，继承自FlexCustomBaseView，然后添加到了普通view上。
由于我不确定它需要显示的frame，我是希望由它的内部内容撑起它的高度。
所以我现在是这样写的
![image](https://user-images.githubusercontent.com/17544458/48693033-14111e00-ec13-11e8-8906-ad7ae320847f.png)
请问这是正确的处理方法吗？还是有更好的解决方案？

**Comment by zhenglibao** [comment]
可以设置flexibleHeight=YES, 然后调用 [view sizeToFit]即可
