### ISSUE TITLE
建议增加新版说明

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#54]
建议增加新版说明！！是修改了bug，还是新增了其他组件，或者功能，我们就可以明确自己目前需不需要更新。只是建议！

**Comment by zhenglibao** [comment]
代码里边有CHANGELOG.MD文件，见：https://github.com/zhenglibao/FlexLib/blob/master/CHANGELOG.md

另外这里也有简单的发版说明：
https://github.com/zhenglibao/FlexLib/releases
