### ISSUE TITLE
关于getSafeArea方法

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#55]
测试发现,用通知方法获取的状态栏高度和getSafeArea:方法内获取的状态栏高度不一致，getSafeArea方法内竖屏状态下状态栏高度尽然是0.0。但是竖屏状态下的状态栏明明存在，并且有高度的啊！！！不知道这是什么原因造成的
![02a219d9-c00c-4d20-91b4-1352be8f628f](https://user-images.githubusercontent.com/20568661/48694371-17a6a400-ec17-11e8-9cdd-1108d1fa9b0e.png)

**Comment by zhenglibao** [comment]
这个是不是在屏幕发生旋转的情况下获取的？如果是旋转的时候系统的状态更新较慢会影响获取到的状态栏高度

**Comment by lztbwlkj** [comment]
嗯 是在旋转屏幕的时候获取的 那我这动态获取修改getSafeArea的大小是行不通了？ 他还影响.xml中的布局，初始进入界面一切都合适，旋转屏幕再转回来就少了20个单位的高度导致我的界面整体上移，导航栏压住了一部分view

**Comment by zhenglibao** [comment]
关于旋转这块暂时也没有特别理想的方案，有一种方法就是直接根据传进来的portait参数和设备类型来写死高度，另外一种就是让getSafeArea返回(0,0,0,0)，然后直接控制self.view的区域即可

**Comment by zhenglibao** [comment]
在 getSafeArea里边像下面这样写不行吗？
```objective-c
statusBarHeight = portrait ? 20 : 0;
```

**Comment by lztbwlkj** [comment]
谢了 我没想到这个 完美解决！！！
