### ISSUE TITLE
关于属性的写法

### ISSUE THREAD

**Issue by YuYangArray** [zhenglibao/FlexLib#56]
我看到Demo中写的属性都是这样的
{
    UIView* _test;
}
是有什么特定的原因吗？
是否可以写成
@property (nonatomic, strong) UIView *test;
如果用下面的一种写法，会造成什么问题呢？如果有问题，是否有解决的方案？
感谢大佬。

**Comment by zhenglibao** [comment]
写成两种形式都可以，之所以写成前面那种形式纯粹是习惯问题，好处是容易和局部变量分开
