### ISSUE TITLE
UIImageView和绝对布局

### ISSUE THREAD

**Issue by YuYangArray** [zhenglibao/FlexLib#57]
由于不能再UIImageView中再写子View，想达成在图片上添加文字或其他效果，就得使用绝对定位position:absolute。这个是看 #16 的问题知道的。
我的项目中有较多的图片上面显示文字或其他叠加图层的情况。所以想问下有没有其他的view能在自身显示图片的同时，直接在xml中添加子视图。
感谢大佬抽空解答。

**Comment by zhenglibao** [comment]
UIImageView可以添加子view的😀

**Comment by YuYangArray** [comment]
![image](https://user-images.githubusercontent.com/17544458/48766655-eb128b00-ecef-11e8-87db-a4179316b608.png)
可是在xml中不是这样的吗？没有</UIImageView>啊。
大佬能给个写法吗？
