### ISSUE TITLE
文本国际化

### ISSUE THREAD

**Issue by haoziy** [zhenglibao/FlexLib#59]
目前文本国际化有解决方案吗

**Comment by zhenglibao** [comment]
有的，demo里边首页上边的那个字符串就会随着系统语言的设置变化而变化，如图
<img width="163" alt="wx20181129-092932 2x" src="https://user-images.githubusercontent.com/1912567/49193232-64c60b00-f3b9-11e8-8974-dd4c024dc62f.png">

使用方式如下：
```xml
<UILabel attr="text:@multilangdemo"/>
```
@符号表示用来引用本地化字符串表里边的字符串
