### ISSUE TITLE
这个框架支持 storyboard 吗

### ISSUE THREAD

**Issue by DevilLeven** [zhenglibao/FlexLib#6]
storyboard 中 使用XML 布局的VC

**Comment by zhenglibao** [comment]
这个没有测试过，不过使用xml的vc等价于用代码创建界面，因此理论上应该是没有问题的😀

**Comment by DevilLeven** [comment]
我简单的试了一下 好像不行  还有 我 用 pod 'FlexLib' 下载的版本是 0.8.0 看来得加上版本号
![image](https://user-images.githubusercontent.com/21081386/34555652-e00ef6d6-f16d-11e7-937d-ef121e3901e6.png)

**Comment by zhenglibao** [comment]
这个你得pod update一下
