### ISSUE TITLE
被引用的控件始终为nil

### ISSUE THREAD

**Issue by powerDJL** [zhenglibao/FlexLib#60]
我在一个tableviewCell 中 使用A视图（一个xml封装成的控件，基于FlexCustomBaseView），tableviewCell 也是用xml布局，xml中也写入了这个控件。但是在tableviewCell 渲染时，A视图始终是nil。
请问A视图需要手动初始化吗？

**Comment by zhenglibao** [comment]
正常情况下是不需要手动初始化的，可以参考demo里边的AttachmentView
方便的话可以把代码粘上来看一下

**Comment by zhenglibao** [comment]
你需要给AuthorBanner控件起名字，然后进行变量绑定
```xml
<AuthorBanner name="a"/>
```
然后在cell.m中才能用变量a使用控件
```objective-c
@property(nonatomic,strong) AuthorBanner* a;
```

**Comment by powerDJL** [comment]
> 你需要给AuthorBanner控件起名字，然后进行变量绑定
> 
> ```
> <AuthorBanner name="a"/>
> ```
> 
> 然后在cell.m中才能用变量a使用控件
> 
> ```objc
> @property(nonatomic,strong) AuthorBanner* a;
> ```

确实忽略这个问题。。。看了demo直接拿来用了。感谢！
刚开始用flexlib  再请问一下， UIImageView 的 layer.cornerRadius 怎么在xml
设置啊。

**Comment by zhenglibao** [comment]
是borderRadius属性
```xml
<UIView nattr="borderRadius:20,bgColor:red" />
```
如果框架里边没有导出某个属性，你也可以用FLEXSET宏自己导出

**Comment by powerDJL** [comment]
> 是borderRadius属性
> 
> ```
> <UIView nattr="borderRadius:20,bgColor:red" />
> ```
> 
> 如果框架里边没有导出某个属性，你也可以用FLEXSET宏自己导出

十分感谢。🌹
