### ISSUE TITLE
FlexScrollView删除添加view的问题

### ISSUE THREAD

**Issue by YuYangArray** [zhenglibao/FlexLib#64]
我在FlexScrollView上添加了一些imageView
![image](https://user-images.githubusercontent.com/17544458/49506272-a1619d00-f8b8-11e8-9e67-c7d214d829a7.png)
这个FlexScrollView是放在一个tableViewCell上的，当cell再次加载model的时候。需要将FlexScrollView上之前添加的view删除，添加新的view。
我注意到有删除view的方法 -(void)removeSubView:(UIView*)view;
但是似乎不能直接删除所有自己添加的View，也不能把FlexScrollView的contentView上的subViews遍历删除。因为contentView上还有两个不是我添加上去的subView
![image](https://user-images.githubusercontent.com/17544458/49506592-64e27100-f8b9-11e8-8e05-c528d852d26d.png)
暂时没有直接删除所有自己添加的subView的方法是吗？
我的想法是继承FlexScrollView，然后在addSubview时把所有自己添加的view计入一个数组。删除时，遍历这个数组，删除view。这个是可行的吧。

**Comment by zhenglibao** [comment]
由于实现的关系，不建议直接往FlexScrollView上动态添加子view，可以在xml中给FlexScrollView嵌入一个FlexContainerView类型的子view，然后往这个子view里边添加或删除

**Comment by YuYangArray** [comment]
好的，非常感谢。
