### ISSUE TITLE
关于SafeArea的计算

### ISSUE THREAD

**Issue by YuYangArray** [zhenglibao/FlexLib#65]
当我需要在一个页面隐藏导航栏时，我是这样写的
![image](https://user-images.githubusercontent.com/17544458/49513155-01613f00-f8cb-11e8-8888-ba231dc080a1.png)
然后我跟踪- (UIEdgeInsets)getSafeArea:(BOOL)portrait方法，发现好像并没有判断导航栏是否隐藏
![image](https://user-images.githubusercontent.com/17544458/49513240-484f3480-f8cb-11e8-9f18-01569c50dca9.png)
这里加个对于隐藏导航栏的判断，应该就可以兼容隐藏导航栏的页面了。

**Comment by zhenglibao** [comment]
这个建议更新到最新的2.1.2版本，里边增加了对导航栏隐藏的判断

**Comment by YuYangArray** [comment]
非常感谢。

**Comment by YuYangArray** [comment]
我更新到2.1.2的版本了。发现是通过!self.navigationController.navigationBar.hidden来判断navigationBar是否隐藏。但是在某些情况下，navigationBar隐藏，hidden不是yes。
通过navigationController.toolbarHidden来判断似乎兼容性更高。

**Comment by zhenglibao** [comment]
多谢指出问题，考虑下个版本加进去

**Comment by zhenglibao** [comment]
另外如果自带的getSafeArea不能满足需求的话，也可以在派生类里边重写这个方法
