### ISSUE TITLE
touchView的多状态

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#66]
touchView默认的状态是touchUpInside,请问按钮点击的其他的个状态,touchView支持吗?

**Comment by zhenglibao** [comment]
不支持，touchview和其他view的onPress事件实现机制是完全一样的，都是通过tap手势实现的，唯一区别就是touchview在按下的时候会自动修改其背景色

**Comment by lztbwlkj** [comment]
那我目前碰到一个微信发语音的 这个按钮你这边<UIButton></UIButton>是不是也不支持？

**Comment by zhenglibao** [comment]
UIButton当然支持（任何UIView的子类都可以在xml里边用），只不过没有导出那么多的属性可以在xml里边用，如果需要的话你可以用FLEXSET宏导出自己的属性

**Comment by lztbwlkj** [comment]
ok 谢谢了

**Comment by lztbwlkj** [comment]
![683b7de8-76e2-49fc-930d-cbebb2075dc1](https://user-images.githubusercontent.com/20568661/49569170-29ee4500-f96e-11e8-805e-2608b677f41b.png)
[self addTarget:action: forControlEvents:n] 这一行我该怎么写,(大神！！请原谅我太菜！！！）

**Comment by lztbwlkj** [comment]
![52419b57-5a65-4656-ada3-72f413e776d8](https://user-images.githubusercontent.com/20568661/49569500-12638c00-f96f-11e8-8cf3-ccabada0141e.png)
[self addTarget: action:forControlEvents:n]这一行我该怎么写？(大神！！请原谅我太菜！！！！）

**Comment by zhenglibao** [comment]
这个如果用代码绑定事件的话就不要写在这个导出属性里了，直接写在owner里边绑定事件就可以了

**Comment by lztbwlkj** [comment]
![4b8742cd-5653-499e-bd9a-c35e61b30b14](https://user-images.githubusercontent.com/20568661/49572290-6b82ee00-f976-11e8-9a8f-666528ba20bc.png)
FLEXSET(outSideOnPress){...}是扩展属性的 有没有扩展类似onPress这种的写法，我想按钮的控件比较特殊，想通过自定义的事件名去绑定对应的不同状态下的交互事件，有没有什么办法？

**Comment by zhenglibao** [comment]
类似onPress这种写法是不能扩展的，关于按钮的事件建议直接在owner加载完xml后直接用代码控制，如下：
```objective-c
[_testBtn addTarget:self action:@selector(switchBgDidChange:) forControlEvents:UIControlEventValueChanged];
```
