### ISSUE TITLE
关于FlexTouchView的onTouch

### ISSUE THREAD

**Issue by YuYangArray** [zhenglibao/FlexLib#68]
我现在需要在view上添加 touchView 
![image](https://user-images.githubusercontent.com/17544458/49863840-22321300-fe3c-11e8-95da-1cc2d9b2924b.png)
在我要给touchView加对饮方法时，发现onTouch是个block，有返回BOOL值，这个BOOL值是具体代表什么意思呢？

然后我去demo中查看类似的情况，发现demo中是通过添加 view，然后在 view 上 添加点击手势完成的。
![image](https://user-images.githubusercontent.com/17544458/49864051-9076d580-fe3c-11e8-9373-2e938db685ab.png)
是添加 touchView 和 view 这两种只是两种不同的实现方法，还是添加 touchView 有什么弊端，所有 demo 中选择了 添加 view?

感谢大佬。

**Comment by zhenglibao** [comment]
FlexTouchView::onTouch这个block并不是用于响应点击事件的，这个block会在按下鼠标和抬起鼠标时各调用一次，参数表示是按下还是抬起，主要用于需要自定义按下鼠标时的外观时使用，比如按下鼠标时改变某个子view的颜色或者形状

如果是想要添加响应事件的话还是要使用手势来实现。

**Comment by YuYangArray** [comment]
好的，明白了。
非常感谢。
