### ISSUE TITLE
UIview 阴影设置问题

### ISSUE THREAD

**Issue by DevilLeven** [zhenglibao/FlexLib#7]
在 tablecell 中设置 UIView 的阴影 ，无论是在代码中直接设置，还是在Xml中，都不能生效。
![image](https://user-images.githubusercontent.com/21081386/34758024-151a13dc-f610-11e7-95c3-c7df3cd18f23.png)
![image](https://user-images.githubusercontent.com/21081386/34758030-1f0aea4c-f610-11e7-9f48-7741671b7d8f.png)

**Comment by zhenglibao** [comment]
问题在于shadowOpacity这个属性没有设置，这个值默认是0，你可以设置成1看看效果。另外这个参数目前还没有导出，你可以自己用FLEXSET扩展一下属性，后续考虑加上
