### ISSUE TITLE
关于输入框自动上移

### ISSUE THREAD

**Issue by YuYangArray** [zhenglibao/FlexLib#74]
我发现键盘弹出，第一响应者输入框自动上移是需要父视图中有ScrollView才可以的。
![image](https://user-images.githubusercontent.com/17544458/50634459-b732b280-0f89-11e9-8096-3207fcd3ff5d.png)
于是我添加了scrollView仅仅是为了UITexgFile能自动上移。
我希望底部的UITextField设置高度后，UITableView能自动补齐剩余高度。但是默认的是UITableView的高度为0。
于是，我只能在代码中通过屏幕高度算出UITableView的高度之后，设置UITableView的高度。
有其他更好的方法吗？
感谢大佬。

**Comment by zhenglibao** [comment]
有一个关于处理键盘的库iqkeyboardmanager，可以了解一下
