### ISSUE TITLE
TextField躲避键盘的BUG

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#76]
问题描述:在IPhone XS Max上,ScrollView中TextField躲避键盘自动上移高度计算有问题(上移过多导致导航栏挡住了TextField)
![default](https://user-images.githubusercontent.com/20568661/53853722-9c200580-4001-11e9-8ced-5630dd4616ad.gif)

TextField上移我发现在IPhone XS Max中计算有失误,起初我以为是我的布局有问题，结果今天在你的设置预加载的Url页面时也出现了，

**Comment by zhenglibao** [comment]
键盘这块确实不够完善，可以禁用该功能，然后自己实现或者使用第三方库，比如IQKeyboardManager

**Comment by lztbwlkj** [comment]
那如何禁用呢？

**Comment by zhenglibao** [comment]
FlexBaseVC里面的avoidKeyboard设置成NO即可
