### ISSUE TITLE
添加其他View

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#77]
一个VC页面继承FlexBaseVC后如何给view上添加高德地图？

**Comment by zhenglibao** [comment]
直接在xml里边声明高德地图的视图类就可以，与UIView的使用没有啥区别

**Comment by lztbwlkj** [comment]
这样子创建<MKMapView name="mkMapView" layout="flex:1,width:100%,alignItems:center" attr="bgColor:white"></MKMapView>

[self.mkMapView setCenterCoordinate:currentLocation.coordinate animated:YES] 这里的animated:没效果了？ 定位成功后地图比例尺不会自动放大了 init创建的就没问题 这里该如何处理
