### ISSUE TITLE
backgroundColor:rgba(255,0,0,1)

### ISSUE THREAD

**Issue by ChengRuipeng** [zhenglibao/FlexLib#78]
attr=" backgroundColor:rgba(255,0,0,1)"
颜色可以支持  rgba(255,0,0,1) 么？

**Comment by zhenglibao** [comment]
颜色支持三种格式
#rrggbb
#aarrggbb
预定义颜色，如white,green,red等

完整参考看这里：https://github.com/zhenglibao/FlexLib/wiki/View-Attributes

**Comment by ChengRuipeng** [comment]
<UIView name="UIView6" layout=" width:100; height:100;" attr=" backgroundColor:rgba(0,128,0,1);">
是否可以用 分号 进行区分？这样可以传 rgba(255,0,0,1) 或者 数组 (1,4,6) 进去，用 逗号 感觉限制比较多

**Comment by zhenglibao** [comment]
只能用逗号分隔，另外颜色也不能用你的写法，应该是  attr="bgColor:#ff0000"这种

**Comment by ChengRuipeng** [comment]
为什么只能用 逗号 分隔？我这边将您的源码修改了一下，按照 分号 分隔的，暂时没遇到什么问题

**Comment by zhenglibao** [comment]
改源码当然可以了
