### ISSUE TITLE
overflow hidden 如何使用

### ISSUE THREAD

**Issue by powerDJL** [zhenglibao/FlexLib#79]
我有个view， 上面水平排列 几个label。 我希望当这几个label 一行显示不下时，隐藏显示不下的label。但是一直不起作用，以下是我的代码：
`<UIView layout="flexDirection: row,height:24,flexShrink:0,display: flex,flexWrap:wrap,overflow: hidden" >
        <UILabel name="label" layout="marginLeft:12,display: block" />
        <UILabel name="label2" layout="marginLeft:12,display: block" />
        <UILabel name="label3" layout="marginLeft:12,display: block" />
</UIView> `

**Comment by zhenglibao** [comment]
可以用视图属性 clipsToBounds:true 来实现这个效果

**Comment by powerDJL** [comment]
> 可以用视图属性 clipsToBounds:true 来实现这个效果

是否可具体说下？感谢了

**Comment by powerDJL** [comment]
我经过测试成功了。需要将代码中将 flexibleWidth 设为 否。 然后xml 文件里attr = "clipsToBounds:true"
感谢大佬。
