### ISSUE TITLE
关于布局浏览器

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#80]
有个问题：在线布局浏览器它只是浏览布局吗？在百度地图中我实际定位获取成功了，小蓝点也显示出来了，但是在在线布局浏览器中是看不到的，我一直以为自己代码有问题了

**Comment by zhenglibao** [comment]
在线布局浏览器确实只是浏览布局。如果想要执行完整的逻辑，可以使用在线加载xml功能: 在设置中勾选”在线加载资源“，然后创建目录索引，之后所有的资源都是实时从网络加载
