### ISSUE TITLE
隐藏view，view上的点击事件仍然有效

### ISSUE THREAD

**Issue by powerDJL** [zhenglibao/FlexLib#81]
```
<UIView layout="flexDirection: row,height:24,flexWrap:wrap" attr="clipsToBounds:true" >
    <FlexTouchView onPress="labelDidPressed" >
        <UILabel name="label" layout="marginLeft:12" />
    </FlexTouchView>
    <FlexTouchView onPress="label2DidPressed" >
        <UILabel name="label2" layout="marginLeft:12" />
    </FlexTouchView>
    <FlexTouchView onPress="label3DidPressed" >
        <UILabel name="label3" layout="marginLeft:12" />
    </FlexTouchView>
</UIView> 
```
一个view上有三个label，由于业务需要，展示不同的数据时，会隐藏其中的一个，或者两个label(label.isHidden = true )。但是,隐藏label后，在label上的点击事件仍然有效。

**Comment by zhenglibao** [comment]
这个点击事件是添加在label的父view上的，你需要隐藏label的父view才对

**Comment by powerDJL** [comment]
> 这个点击事件是添加在label的父view上的，你需要隐藏label的父view才对
父view被隐藏，三个label都没了，我要隐藏的其中一，二个label
是不是可以写成下面这样？lable上加点击事件。
```
<UILabel name="label3" layout="marginLeft:12" >
      <FlexTouchView onPress="label3DidPressed"  />
</UILabel>
```

**Comment by powerDJL** [comment]
> > 这个点击事件是添加在label的父view上的，你需要隐藏label的父view才对
> 
> 父view被隐藏，三个label都没了，我要隐藏的其中一，二个label
> 是不是可以写成下面这样？lable上加点击事件。
> 
> ```
> <UILabel name="label3" layout="marginLeft:12" >
>       <FlexTouchView onPress="label3DidPressed"  />
> </UILabel>
> ```

我试了，这样不行。😭，我再想想吧。

**Comment by lztbwlkj** [comment]
你需要隐藏的是FlexTouchView 而不是UIView

**Comment by lztbwlkj** [comment]
> > > 这个点击事件是添加在label的父view上的，你需要隐藏label的父view才对
> > 
> > 
> > 父view被隐藏，三个label都没了，我要隐藏的其中一，二个label
> > 是不是可以写成下面这样？lable上加点击事件。
> > ```
> > <UILabel name="label3" layout="marginLeft:12" >
> >       <FlexTouchView onPress="label3DidPressed"  />
> > </UILabel>
> > ```
> 
> 我试了，这样不行。😭，我再想想吧。

你需要隐藏的是FlexTouchView 而不是UIView

**Comment by powerDJL** [comment]
> > > > 这个点击事件是添加在label的父view上的，你需要隐藏label的父view才对
> > > 
> > > 
> > > 父view被隐藏，三个label都没了，我要隐藏的其中一，二个label
> > > 是不是可以写成下面这样？lable上加点击事件。
> > > ```
> > > <UILabel name="label3" layout="marginLeft:12" >
> > >       <FlexTouchView onPress="label3DidPressed"  />
> > > </UILabel>
> > > ```
> > 
> > 
> > 我试了，这样不行。😭，我再想想吧。
> 
> 你需要隐藏的是FlexTouchView 而不是UIView

嗯，这是个思路，label.superView 。我之前把FlexTouchView理解成了原生view的touch手势了。
