### ISSUE TITLE
关于FlexModalView

### ISSUE THREAD

**Issue by lztbwlkj** [zhenglibao/FlexLib#82]
对于FlexModelView可否单独分离出来写xml，再将它和VC结合起来使用，show呼出。而不是将它写在FlexBaseVC的xml中，我在FlexCustomBaseView的xml中看到 <AttachmentView/>，引入方式，不知这种方法可否（我试过，但是不能呼出）

**Comment by zhenglibao** [comment]
FlexModelView本来是提供一个简单快捷的方式弹出view控件的，如果分离出来的话，可以直接使用FlexCustomBaseView制作组件，然后手动呼出，就没有必要使用FlexModelView了。

**Comment by lztbwlkj** [comment]
好的 谢了
