### ISSUE TITLE
布局配置文件 可以继承吗

### ISSUE THREAD

**Issue by qgxqgx** [zhenglibao/FlexLib#84]
布局配置文件 可以继承吗

**Comment by zhenglibao** [comment]
不能继承，但是可以把不变的部分拆分出独立的xml文件，然后做成组件，提高复用性

**Comment by lztbwlkj** [comment]
布局配置预览的URL怎么Run一次APP就需要设置一次，我也点击保存了

**Comment by zhenglibao** [comment]
> 布局配置预览的URL怎么Run一次APP就需要设置一次，我也点击保存了

不会的啊，你是不是换模拟器了或者把app删掉重装了

**Comment by lztbwlkj** [comment]
没换过
另外我发现在布局浏览器中，点击事件是无效的：
加我qq吧！有问题也方便交流

**Comment by zhenglibao** [comment]
> 没换过模拟器；
> 另外我发现在布局浏览器中，点击事件是无效的：
> 加我qq吧！有问题也方便交流（903607388）

布局浏览器只是用来查看界面，不带有任何功能的。可以加入qq群：687398178
