### ISSUE TITLE
在Framework中使用FlexLib 无法找到xml文件

### ISSUE THREAD

**Issue by powerDJL** [zhenglibao/FlexLib#85]
使用环境大概是这样，工程中使用pod引入FlexLib，工程中另一个Framework使用的了FlexLib布局。在Framework中的UI组件会找不到相应的xml文件，经过查看发现，FlexLib中 使用的bundle是 mainBundle，导致在load xml路径是在主工程中，而不是在Framework中。如果能有个自定义bundle的方法，就可以解决这个问题了

**Comment by powerDJL** [comment]
自问自答吧，用自定义加载方法FlexSetCustomLoadFunc  可以修改，但是个全局的修改，可能会有冲突。

**Comment by zhenglibao** [comment]
也可以重写owner里面的bundleForRes方法，返回对应的bundle即可。

**Comment by powerDJL** [comment]
> 也可以重写owner里面的bundleForRes方法，返回对应的bundle即可。

好的。感谢回复。
