### ISSUE TITLE
一个缓存问题

### ISSUE THREAD

**Issue by powerDJL** [zhenglibao/FlexLib#86]
FlexLib会缓存xml文件在Documents文件夹下，并通过CFBundleVersion 来区分版本，并在升级的时候清理缓存文件。
CFBundleVersion 字符串表示的是build版本， 重复的可能性很大。
用CFBundleShortVersionString 来区分版本，可能会好一些。
或者缓存放在 /Library/Caches 放在这里也可以。升级的时候不会保存这个目录。

**Comment by zhenglibao** [comment]
正常来讲CFBundleVersion都应该是单调递增的吧
