### ISSUE TITLE
UICollectionViewCell的计算大小

### ISSUE THREAD

**Issue by YuYangArray** [zhenglibao/FlexLib#87]
/*
 * 计算cell大小，使用该方法之前需要在onInit方法中设置rootview的宽度和高度是否可变
 * 只有高度或者宽度可变才有必要调用该方法计算匹配的大小
 */
-(CGSize)calculateSize:(CGSize)szLimit;

我看到文件中有这么一段计算UICollectionViewCell的方法，但是当我把flexibleHeight设置为yes后。使用calculateSize方法，传入什么size，就返回什么size。似乎并没有计算size。

**Comment by zhenglibao** [comment]
这个和你的xml有关系，如果你的xml最外面的view使用了诸如flex:1之类的属性的话就不会由内容计算大小

**Comment by YuYangArray** [comment]
我之前想到了可能是这个问题，下图是我的xml，已经删除了flex:1
![image](https://user-images.githubusercontent.com/17544458/60333977-03a4fb00-99cd-11e9-9aa8-f39c170fd28c.png)
然后在调试中，可以看到，rootview的范围明显大于内容视图。
![image](https://user-images.githubusercontent.com/17544458/60333930-e53eff80-99cc-11e9-87ef-6008b8b2a740.png)

**Comment by zhenglibao** [comment]
设置flexibleHeight = YES了吗?

**Comment by YuYangArray** [comment]
有的
![image](https://user-images.githubusercontent.com/17544458/60340058-27703d00-99dd-11e9-8c89-2fd298de5432.png)
然后高度这边没找到示例，按照tableViewCell的方式写的
![image](https://user-images.githubusercontent.com/17544458/60340112-4cfd4680-99dd-11e9-85ea-f0347315abd3.png)

**Comment by zhenglibao** [comment]
方便的话可以发个demo出来看看

**Comment by YuYangArray** [comment]
[collectionCell.zip](https://github.com/zhenglibao/FlexLib/files/3343750/collectionCell.zip)
文件已上传
我在写这个demo的时候，先随手写了个cell，就是demo中的CollectionViewInfoCell，是可以计算高度的。
之后把不能计算高度的那个cell拖进来，是QWMineUserCVCell，就不能计算高度了。

**Comment by zhenglibao** [comment]
在QWMineUserCVCell的onInit中
self.rootView.flexibleHeight = YES;
没有起作用,正确的应该是
self.rootview.flexibleHeight = YES;

这个根本原因是FlexCollectionCell的rootview属性命名不规范造成的，为了避免再次出现此类问题，已经在2.3.3中修改该属性为rootView，统一了该属性的命名，请更新该版本

**Comment by YuYangArray** [comment]
好的，非常感谢。
