### ISSUE TITLE
marginTop和aspectRatio会导致冲突

### ISSUE THREAD

**Issue by YuYangArray** [zhenglibao/FlexLib#88]
我这边发现，当同时存在marginTop和aspectRatio时，会产生冲突。
![image](https://user-images.githubusercontent.com/17544458/60477494-ef554c80-9cb1-11e9-85ea-052120ac9bb6.png)
的实际显示效果为
![image](https://user-images.githubusercontent.com/17544458/60477504-fb410e80-9cb1-11e9-95f8-6162da51b900.png)
想请你确认一下，是只有我这边会出现这个问题，还是都会出现这个问题。

**Comment by zhenglibao** [comment]
这个需要检查你的布局，目前还没有其他人发现冲突的问题

**Comment by YuYangArray** [comment]
我新建了demo,使用了最简单的写法，没有找出问题。可以麻烦帮忙看一下吗？
文件已上传.
[marginTop.zip](https://github.com/zhenglibao/FlexLib/files/3349681/marginTop.zip)

**Comment by zhenglibao** [comment]
使用aspectRatio的话，需要明确指定宽或者高，比如指定width:100%，如果不指定的话属于未定义行为

**Comment by YuYangArray** [comment]
那如果，我的需求是，长宽比为1。同时，左右分别距离屏幕17pt。
这种情况就只能到页面里面
[self.view setLayoutAttr:@"width" Value:[NSString stringWithFormat:@"%f", SCREEN_WIDTH - 17 * 2]];
这样写了是吗?有没有啥更好的写法？

**Comment by zhenglibao** [comment]
假设A为全屏幕，B是子视图，如果想B的宽度等于屏幕宽度-17*2，可以:
在B和A中间套一视图C，c的左右margin等于17，然后B的宽度为100%即可

**Comment by YuYangArray** [comment]
好的，非常感谢
