### ISSUE TITLE
提一点小建议

### ISSUE THREAD

**Issue by yizzuide** [zhenglibao/FlexLib#9]
一直在想iOS什么时候有个XML布局的方式，框架想法很不错，但一般项目中都有一个要继承的Base控制器，这样就不能再继承其它控制器，是不是可以通过对UIViewController添加分类，再通过Runtime添加属性或hook生命周期来做些框架的事情，建议最好不要让开发者继承一个类，这样比较被动。。

**Comment by zhenglibao** [comment]
如果只是想使用xml布局的话，并不是一定要从FlexBaseVC继承，你也可以从UIViewController继承，然后使用FlexFrameView来加载xml，然后将这个view添加到你的viewcontroller上就可以了。使用FlexBaseVC的好处是，一是自动调整safe area，另外一个是自动躲避键盘遮挡，这两个需求都不是必须的。

**Comment by yizzuide** [comment]
好的，Thx

**Comment by yizzuide** [comment]
楼主更新好快啊，开源项目就需要这种持续维护的热度。。

**Comment by Homin818** [comment]
是否可以将 xml 换成类似 vue.js 的样式分离出来？

**Comment by zhenglibao** [comment]
xml本身支持将布局属性和视图属性分离出来放到独立的style文件里边，这样可以复用样式。
