### ISSUE TITLE
能不能新增一个xml导入第三方的例子

### ISSUE THREAD

**Issue by yang0000meng** [zhenglibao/FlexLib#91]
尝试使用SGPagingView在flexlib 中 一直不显示 ，也不报错
用rootView.addSubview(） 才显示 一部分。
能不能新增一个xml导入第三方的例子。
ios新手 FlexLib 资料不好找呀

**Comment by zhenglibao** [comment]
使用自定义view或者第三方view的文档：
https://github.com/zhenglibao/FlexLib/wiki/Tutorial-4:-Use-custom-view-in-xml-layout

理论上来说，使用第三方view和系统的view没有任何区别，能否直接使用关键在于是否支持init方法，如果支持，则直接使用，否则重写owner的createView方法，返回自定义创建的对象即可，如果需要视图属性，可以通过FLEXSET宏进行扩展。VSCode的提示需要自己配置。
