### ISSUE TITLE
FlexCollectionCell 在 swift 下问题

### ISSUE THREAD

**Issue by Angelnil** [zhenglibao/FlexLib#96]
FlexCollectionCell 在 swift 项目或者是混合项目中  resName 会带上项目名称。则 xml 文件加载不出来 。也不能自定义 xml 文件的名称 。
       
  +(FlexRootView*)loadWithNodeFile:(NSString*)resName Owner:(NSObject*)owner
      {
          if(resName==nil){
              resName = NSStringFromClass([owner class]);
          }

    FlexRootView* root = [[FlexRootView alloc]init];
    root->_owner = owner;

    FlexNode* node = [FlexNode loadNodeFromRes:resName Owner:owner];
    if(node != nil){
        UIView* sub ;

        @try{
            sub = [node buildViewTree:owner
                             RootView:root];
        }@catch(NSException* exception){
            NSLog(@"Flexbox: FlexRootView exception occured - %@",exception);
        }

        if(sub != nil && ![sub isKindOfClass:[FlexModalView class]])
        {
            [root addSubview:sub];
        }
    }
    return root;
  }

**Comment by zhenglibao** [comment]
FlexCollectionCell的派生类需要使用@objc关键字来声明，这样就不会带有项目名称前缀，参考demo中FlexBaseTableCell的例子
